- id: '1597135386283'
  alias: Office On Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.sw_1_level
    - light.sw_2_level
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != ''off'' }}'
  action:
  - service: light.turn_on
    entity_id: light.office_lights
    data_template:
      brightness: '{{ trigger.to_state.attributes.brightness }}'
  - wait_template: '{{ is_state_attr(''light.office_lights'', ''brightness'', trigger.to_state.attributes.brightness)}}'
    timeout: 00:00:05
  - delay: 00:00:01
  mode: single
- id: '1597137681107'
  alias: Office Off Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.sw_1_level
    - light.sw_2_level
    to: 'off'
  condition:
  - condition: state
    entity_id: light.office_lights
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.office_lights
  - wait_template: '{{ is_state(''light.office_lights'', ''off'')}}'
    timeout: 00:00:05
  mode: single
- id: '1597177364212'
  alias: SW10 Turn On
  description: ''
  trigger:
  - device_id: 41823a1558d94f99abfcd3723cd2a078
    domain: switch
    entity_id: switch.lzw30_switch_switch
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 297b1b6240b54d768fa7fae65efbdfa4
    domain: switch
    entity_id: switch.zmnhvdx_flush_dimmer_0_10v_switch
    type: turn_on
  - device_id: 6c91686cbcfe495683169df473bfcb23
    domain: switch
    entity_id: switch.multilevel_power_switch_switch
    type: turn_on
  mode: single
- id: '1597177448278'
  alias: SW10 Turn Off
  description: ''
  trigger:
  - device_id: 41823a1558d94f99abfcd3723cd2a078
    domain: switch
    entity_id: switch.lzw30_switch_switch
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: 297b1b6240b54d768fa7fae65efbdfa4
    domain: switch
    entity_id: switch.zmnhvdx_flush_dimmer_0_10v_switch
    type: turn_off
  - device_id: 6c91686cbcfe495683169df473bfcb23
    domain: switch
    entity_id: switch.multilevel_power_switch_switch
    type: turn_off
  mode: single
- alias: Test Lights On
  trigger:
  - platform: state
    entity_id:
    - light.test01_dimmer_level
    - light.test02_dimmer_level
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != ''off'' }}'
  action:
  - service: light.turn_on
    entity_id: light.test_light_group
    data_template:
      brightness: '{{ trigger.to_state.attributes.brightness }}'
  id: b99a07a8ce9e40bd86f8b15286d2a679
- alias: Test Lights Off
  trigger:
  - platform: state
    entity_id:
    - light.test01_dimmer_level
    - light.test02_dimmer_level
    to: 'off'
  condition:
  - condition: state
    entity_id: light.test_light_group
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.office_lights
  id: 7392cee5cfb64c57a87cf73ccf32bff5
- id: '1604911784468'
  alias: tst
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.test01_dimmer_level
    - light.test02_dimmer_level
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != ''off'' }}'
  action:
  - service: light.turn_on
    data_template:
      brightness: '{{ trigger.to_state.attributes.brightness }}'
    entity_id: light.test_light_group
  mode: single
