- id: '1597135386283'
  alias: Office On Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.sw_1_level
    - light.sw_2_level
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != 'off' }}"
  action:
  - service: light.turn_on
    entity_id: light.office_lights
    data_template:
      brightness: "{{ trigger.to_state.attributes.brightness }}"
  - wait_template: "{{ is_state_attr('light.office_lights', 'brightness', trigger.to_state.attributes.brightness)}}"
    timeout: '00:00:05'
  - delay: '00:00:01'
  mode: single
- id: '1597137681107'
  alias: Office Off Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.sw_1_level
    - light.sw_2_level
    to: 'off'
  condition:
  - condition: state
    entity_id: light.office_lights
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.office_lights
  - wait_template: "{{ is_state('light.office_lights', 'off')}}"
    timeout: '00:00:05'
  mode: single
- id: '1597177364212'
  alias: SW10 Turn On
  description: ''
  trigger:
  - device_id: 41823a1558d94f99abfcd3723cd2a078
    domain: switch
    entity_id: switch.lzw30_switch_switch
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 297b1b6240b54d768fa7fae65efbdfa4
    domain: switch
    entity_id: switch.zmnhvdx_flush_dimmer_0_10v_switch
    type: turn_on
  - device_id: 6c91686cbcfe495683169df473bfcb23
    domain: switch
    entity_id: switch.multilevel_power_switch_switch
    type: turn_on
  mode: single
- id: '1597177448278'
  alias: SW10 Turn Off
  description: ''
  trigger:
  - device_id: 41823a1558d94f99abfcd3723cd2a078
    domain: switch
    entity_id: switch.lzw30_switch_switch
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: 297b1b6240b54d768fa7fae65efbdfa4
    domain: switch
    entity_id: switch.zmnhvdx_flush_dimmer_0_10v_switch
    type: turn_off
  - device_id: 6c91686cbcfe495683169df473bfcb23
    domain: switch
    entity_id: switch.multilevel_power_switch_switch
    type: turn_off
  mode: single
- id: '1597178026933'
  alias: Kitchen Lights On
  description: ''
  trigger:
  - device_id: 35a658320aa44eaca0ed3517731cfa44
    domain: light
    entity_id: light.sw_11_level
    platform: device
    type: turned_on
  - device_id: beb47bc78aea4a1e93e84f0747e65bcf
    domain: light
    entity_id: light.sw_12_level
    platform: device
    type: turned_on
  condition: []
  action:
  - delay: 00:00:02
  - data: {}
    service: script.turn_on_kitchen_lights
  mode: single
- id: '1597178064425'
  alias: Kitchen Lights Off
  description: ''
  trigger:
  - device_id: 35a658320aa44eaca0ed3517731cfa44
    domain: light
    entity_id: light.sw_11_level
    platform: device
    type: turned_off
  - device_id: beb47bc78aea4a1e93e84f0747e65bcf
    domain: light
    entity_id: light.sw_12_level
    platform: device
    type: turned_off
  condition: []
  action:
  - data: {}
    service: script.turn_off_kitchen_lights
  mode: single
