mqtt:
  broker: localhost
  port: 1883


sensor:
  - platform: mqtt
    name: ZWaveNode_2
    state_topic: "OpenZWave/1/node/2/instance/1/commandclass/114/value/1125899954847767/"
    value_template: '{{ value_json.Value }}'
    unique_id: ZWaveNode_2
    
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

          
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

# for testing
switch:
  - platform: template
    switches:
      test_switch:
        friendly_name: "Test Switch Office"
        turn_on:
          #service: switch.turn_on
          #data:
          #  entity_id: switch.skylight_open
        turn_off:
          #service: switch.turn_off
          #data:
          #  entity_id: switch.skylight_close

