# - platform: group
#   name: Office Lights
#   entities:
#     - light.sw_1_level
#     - light.sw_2_level
# - platform: group
#   name: Kitchen Lights
#   entities:
#     - light.sw_11_level
#     - light.sw_12_level
#- platform: group
#  name: Test Light Group
#  entities:
#    - light.test_1_dimmer_level
#    - light.test_2_dimmer_level

# - platform: template
#   lights:
#     test_3:
#       friendly_name: "Test Light 3"
#       turn_on:
#       turn_off:
#       set_level:

# - platform: template
#   lights:
#     test_4:
#       friendly_name: "Test Light 4"
#       turn_on:
#       turn_off:
#       set_level:

# - platform: template
#   lights:
#     test_5:
#       friendly_name: "Test Light 5 Open Office"
#       turn_on:
#       turn_off:
#       set_level:
      
# - platform: template
#   lights:
#     test_17:
#       friendly_name: "Test Light 17 Open Office"
#       turn_on:
#       turn_off:
#       set_level:
# - platform: template
#   lights:
#     test_18:
#       friendly_name: "Test Light 18 Open Office"
#       turn_on:
#       turn_off:
#       set_level:

- platform: template
  lights:
    dining_virtual_light:
      friendly_name: "Dining Room Linear"
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.sw_1_reception
          brightness: 255
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.sw_1_reception
      set_level:
        - service: light.turn_on
          data:
            entity_id: light.sw_1_reception
            brightness: 255
        - service: light.turn_on
          data:
            entity_id: light.zmnhvdx_flush_dimmer_0_10v_level
            brightness: "{{ brightness }}"

- platform: template
  lights:
    office_virtual_light:
      friendly_name: "Open Office Linear"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.switch_sw_16_open_office
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.switch_sw_16_open_office
      set_level:
        - service: switch.turn_on
          data:
            entity_id: switch.switch_sw_16_open_office
        - service: light.turn_on
          data:
            entity_id: light.zmnhvdx_flush_dimmer_0_10v_level_2
            brightness: "{{ brightness }}"
        
