- platform: group
  name: Office Lights
  entities:
    - light.sw_1_level
    - light.sw_2_level
- platform: group
  name: Kitchen Lights
  entities:
    - light.sw_11_level
    - light.sw_12_level
#- platform: group
#  name: Test Light Group
#  entities:
#    - light.test_1_dimmer_level
#    - light.test_2_dimmer_level

- platform: template
  lights:
    test_3:
      friendly_name: "Test Light 3"
      turn_on:
      turn_off:
      set_level:

- platform: template
  lights:
    test_4:
      friendly_name: "Test Light 4"
      turn_on:
      turn_off:
      set_level:

- platform: template
  lights:
    test_5:
      friendly_name: "Test Light 5 Open Office"
      turn_on:
      turn_off:
      set_level:
      
- platform: template
  lights:
    test_17:
      friendly_name: "Test Light 17 Open Office"
      turn_on:
      turn_off:
      set_level:
- platform: template
  lights:
    test_18:
      friendly_name: "Test Light 18 Open Office"
      turn_on:
      turn_off:
      set_level:

- platform: template
  lights:
    kitchen_virtual_light:
      friendly_name: "Kitchen Virtual Light"
      turn_on:
        service: light.turn_on
        data:
          entity_id: light.test_3
          brightness: 255
      turn_off:
        service: light.turn_off
        data:
          entity_id: light.test_3
      set_level:
        - service: light.turn_on
          data:
            entity_id: light.test_3
            brightness: 255
        - service: light.turn_on
          data:
            entity_id: light.test_4
            brightness: "{{ brightness }}"

- platform: template
  lights:
    office_virtual_light:
      friendly_name: "Open Office Virtual Light"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.test_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.test_switch
      set_level:
        - service: switch.turn_on
          data:
            entity_id: switch.test_switch
        - service: light.turn_on
          data:
            entity_id: light.test_5
            brightness: "{{ brightness }}"
        
